# Generated by Django 3.2 on 2021-04-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=1234, max_length=20),
            preserve_default=False,
        ),
    ]
